### ISSUE TITLE
News and Events page always routes to news 1

### ISSUE THREAD

**Issue by gbenziv** [vincebanzon/crestcebu-src#8]
Found in pages deployed from: https://github.com/vincebanzon/crestcebu-src/pull/6
Environment: Desktop
Browser: Microsoft Edge 

Steps to reproduce:
1. Go to homepage - https://vincebanzon.github.io/crestcebu/
2. Scroll to the bottom (footer)
3. Under Useful Links, select News and Events
4. Select any news/event (except the first)

EXPECTATION:
- Routes to the page of the selected item 
   - (e.g. https://vincebanzon.github.io/crestcebu/news/2 if second item is selected)

ACTUAL:
- Always routes to https://vincebanzon.github.io/crestcebu/news/1

**Comment by vincebanzon** [comment]
This is expected since there is currently no data sets that is connected from the database.
To fix this issue, data should be coming from the database.

**Comment by gbenziv** [comment]
thanks @vincebanzon , closing
