### ISSUE TITLE
Messenger icon overlaps "Go back to top" button

### ISSUE THREAD

**Issue by gbenziv** [vincebanzon/crestcebu-src#9]
Found in pages deployed from: https://github.com/vincebanzon/crestcebu-src/pull/6
Environment: Desktop
Browser: Microsoft Edge 

Steps to reproduce:
1. Go to homepage - https://vincebanzon.github.io/crestcebu/
2. Scroll to the bottom
3. Check the icons/buttons in the lower right

EXPECTATION:
- "Go back to top" should be below the messenger button/icon

ACTUAL:
- Messenger icon overlaps "Go back to top" button

SCREENSHOT:
![image](https://user-images.githubusercontent.com/9212261/132936426-a10bb7f7-b24c-47f6-932e-d276a7fb2ca4.png)

**Comment by vincebanzon** [comment]
How about i.remove nalang ni ang go-to-top button?
I will try though to move it.

**Comment by gbenziv** [comment]
sige @vincebanzon . if kuti siya, pwede ra iremove nalang nato
